
angularmoviemasher:
  build: ../../../
  dockerfile: ./Dockerfile
  ports:
    - "8080:80"
  volumes:
    - "../../../log:/tmp/moviemasher/log/"
    - "../../../src:/var/www/html/angular-moviemasher/src"
    - "../../../app:/var/www/html/angular-moviemasher/app"
    - "../../../dist:/var/www/html/angular-moviemasher/dist"
    - "../../../bower_components:/var/www/html/angular-moviemasher/bower_components"
moviemasherrb:
  image: moviemasher/moviemasher.rb
  volumes_from:
    - angularmoviemasher
  command: process_loop -v debug
  tty: true
